/**
 * createEsbuildMfPlugin — esbuild Plugin for Module Federation (production build).
 *
 * This plugin wires Module Federation into Angular's native esbuild pipeline:
 *
 *  1. Externalises singleton shared packages so they are NOT bundled into
 *     remote chunks (the host provides them at runtime).
 *  2. Code-splits every exposed module into a separate output chunk so that
 *     the host can lazy-load each remote's exposed surface independently.
 *  3. Uses `onEnd` + `metafile` to resolve actual hashed chunk filenames and
 *     writes the final `remoteEntry.js` with correct paths to the output dir.
 *
 * Size constraint (Requirement 3.7):
 *   The emitted `remoteEntry.js` MUST be < 5 KB when gzip-compressed.
 *
 * Requirements: 3.1, 3.2, 3.4, 3.5, 3.6, 3.7
 */

import type { Plugin, OnResolveArgs, OnLoadArgs } from 'esbuild';
import { generateRemoteEntry } from './generate-remote-entry.js';
import type { EsbuildMfPluginOptions, ModuleFederationConfig } from '../types/index.js';
import { basename, extname } from 'node:path';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Virtual module filter — matches `virtual:mf-entry` exactly. */
const VIRTUAL_ENTRY_FILTER = /^virtual:mf-entry$/;

/** Namespace used for the virtual remote entry module. */
const VIRTUAL_MF_NAMESPACE = 'virtual-mf-entry';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildOutputsMapFallback(exposes: Record<string, string>): Map<string, string> {
  const map = new Map<string, string>();
  for (const [key, sourcePath] of Object.entries(exposes)) {
    const entryName = key.startsWith('./') ? key.slice(2) : key;
    map.set(sourcePath, `./${entryName}.js`);
  }
  return map;
}

function toMfConfig(options: EsbuildMfPluginOptions): ModuleFederationConfig {
  return {
    name: options.name,
    filename: options.filename,
    exposes: options.exposes,
    shared: options.shared,
  };
}

// ---------------------------------------------------------------------------
// Plugin factory
// ---------------------------------------------------------------------------

/**
 * Creates an esbuild `Plugin` that adds Module Federation capabilities to an
 * Angular production build.
 *
 * Requirements: 3.1, 3.2, 3.4, 3.5, 3.6, 3.7
 */

// WeakMap to hold pending remoteEntry.js content keyed by plugin instance.
// Using WeakMap avoids adding extra properties to the plugin object that
// esbuild would reject as "invalid options".
const pendingEntryMap = new WeakMap<Plugin, string>();

/**
 * Retrieves the pending remoteEntry.js JS string generated by the last esbuild
 * run for the given plugin. Called by application-builder.ts AFTER Angular
 * copies output files to dist/ (since onEnd fires before that copy).
 */
export function getPendingRemoteEntryJs(plugin: Plugin): string | undefined {
  return pendingEntryMap.get(plugin);
}

export function createEsbuildMfPlugin(options: EsbuildMfPluginOptions): Plugin {
  const plugin: Plugin = {
    name: 'angular-mf-esbuild',

    setup(build) {
      const hasExposes = Object.keys(options.exposes).length > 0;

      // ------------------------------------------------------------------
      // Enable metafile so onEnd can resolve actual hashed chunk filenames
      // ------------------------------------------------------------------
      if (hasExposes) {
        build.initialOptions.metafile = true;
      }

      // ------------------------------------------------------------------
      // 1. Collect singleton externals (Requirement 3.4)
      // ------------------------------------------------------------------
      const singletonExternals: string[] = [];
      for (const [pkgName, cfg] of Object.entries(options.shared)) {
        if (cfg.singleton) {
          singletonExternals.push(pkgName);
        }
      }

      if (singletonExternals.length > 0) {
        if (!options.isDev) {
          // ── PRODUCTION ────────────────────────────────────────────────────
          // Mark shared singletons as external via initialOptions so esbuild
          // leaves bare `import "@angular/core"` statements in the output.
          // Angular's internal plugins resolve imports before onResolve hooks
          // fire, so initialOptions.external is the only reliable hook point.
          // The application-builder then builds each dep into dist/shared/ and
          // injects a <script type="importmap"> into index.html so the browser
          // can resolve these bare imports.
          build.initialOptions.external = [
            ...(build.initialOptions.external ?? []),
            ...singletonExternals,
          ];
        } else {
          // ── DEV SERVER ───────────────────────────────────────────────────
          // Rewrite shared imports to /mf-shared/<pkg>.js so our Vite
          // middleware can intercept and serve them on-the-fly.
          const sharedRegex = new RegExp(
            `^(${singletonExternals.map(e => e.split('/').join('\\/') ).join('|')})$`
          );
          build.onResolve({ filter: sharedRegex }, args => {
            if (args.importer.includes('mf-entry')) return null;
            return { path: `/mf-shared/${args.path}.js`, external: true };
          });
        }
      }

      // ------------------------------------------------------------------
      // 1b. Inject exposed source paths into entryPoints (Requirement 3.2)
      // ------------------------------------------------------------------
      if (hasExposes) {
        if (Array.isArray(build.initialOptions.entryPoints)) {
          const entries = build.initialOptions.entryPoints as any[];
          for (const sourcePath of Object.values(options.exposes)) {
            entries.push(sourcePath);
          }
        } else if (typeof build.initialOptions.entryPoints === 'object') {
          for (const [key, sourcePath] of Object.entries(options.exposes)) {
            const entryName = key.startsWith('./') ? key.slice(2) : key;
            (build.initialOptions.entryPoints as Record<string, string>)[entryName] = sourcePath;
          }
        }
      }

      // ------------------------------------------------------------------
      // 2. onResolve: virtual:mf-entry → virtual-mf-entry namespace
      //    (Requirement 3.1, 3.6)
      // ------------------------------------------------------------------
      build.onResolve({ filter: VIRTUAL_ENTRY_FILTER }, (args: OnResolveArgs) => {
        return {
          path: args.path,
          namespace: VIRTUAL_MF_NAMESPACE,
        };
      });

      // ------------------------------------------------------------------
      // 3. onLoad: virtual-mf-entry → empty placeholder
      //    The real remoteEntry.js is written in onEnd with correct paths.
      // ------------------------------------------------------------------
      build.onLoad(
        { filter: /.*/, namespace: VIRTUAL_MF_NAMESPACE },
        async (_args: OnLoadArgs) => {
          return {
            contents: '/* mf-placeholder */',
            loader: 'js',
          };
        },
      );

      // ------------------------------------------------------------------
      // 4. onEnd: resolve actual hashed chunk paths from metafile, then
      //    write the final remoteEntry.js to the output directory.
      //
      //    This is the key fix for production builds. esbuild appends content
      //    hashes to output filenames (e.g. GreetingComponent-AW272VWV.js).
      //    We use the metafile to find the exact output filename for each
      //    exposed source, then generate remoteEntry.js with the correct paths.
      // ------------------------------------------------------------------
      if (hasExposes) {
        build.onEnd(async (result) => {
          const metafile = result.metafile;
          if (!metafile) {
            console.warn('[MF] metafile not available — remoteEntry.js cannot be generated.');
            return;
          }



          const buildOutputs = new Map<string, string>();

          for (const [outputPath, outputInfo] of Object.entries(metafile.outputs)) {
            const entryPoint = outputInfo.entryPoint;
            if (!entryPoint) continue;

            const normalizedEntry = entryPoint.replace(/^\.\//, '');

            for (const [, sourcePath] of Object.entries(options.exposes)) {
              const normalizedSource = sourcePath.replace(/^\.\//, '');

              if (
                normalizedEntry === normalizedSource ||
                normalizedEntry.endsWith('/' + normalizedSource) ||
                normalizedEntry.endsWith(normalizedSource)
              ) {
                // Use only the basename — remoteEntry.js and chunks are co-located
                buildOutputs.set(sourcePath, './' + basename(outputPath));
              }
            }
          }

          if (buildOutputs.size === 0) {
            console.warn('[MF] Could not match any exposed modules in metafile. Falling back to unhashed paths.');
            // Fallback: use entryName-based paths (no hash)
            for (const [key, sourcePath] of Object.entries(options.exposes)) {
              const entryName = key.startsWith('./') ? key.slice(2) : key;
              buildOutputs.set(sourcePath, `./${entryName}.js`);
            }
          }

          const config = toMfConfig(options);
          const js = await generateRemoteEntry(config, buildOutputs);

          // Store in WeakMap — application-builder.ts reads this AFTER Angular
          // copies build artifacts to dist/ (esbuild onEnd fires before that).
          pendingEntryMap.set(plugin, js);
          console.log('[MF] remoteEntry.js generated, pending write after Angular output copy.');
        });
      }
    },
  };

  return plugin;
}
